apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: scroll-share
data:
  HOST: "0.0.0.0"
  PORT: "8081"
  DATABASE_URL: "postgresql://auth_user:auth_dev_password@scroll-share-db-rw.scroll-share:5432/scrollshare?options=-csearch_path%3Dauth"
  RUST_LOG: "info,auth_service=debug"
